import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "../global.css";

import { getQueryClient } from "@app/get-query-client";
import { WebVitals } from "@components/web-vitals";
import StyledComponentsRegistry from "@lib/registry";
import { LandingPageProvider } from "@providers/LandingPageProviders";
import Providers from "@providers/tanstackQueryProviders";
import { getProductListService } from "@services/product-services";

if (process.env.NEXT_PUBLIC_API_MOCKING === "enabled") {
  require("@import/lib/mocks/msw-init");
}

const MulishFont = Mulish({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();

  // Prefetch data without awaiting
  queryClient.prefetchQuery({
    queryKey: ["get-product-list"],
    queryFn: getProductListService,
  });

  const dehydratedState = dehydrate(queryClient);
  return (
    <html lang="en">
      <body className={MulishFont.className}>
        <Providers>
          <HydrationBoundary state={dehydratedState}>
            <StyledComponentsRegistry>
              <LandingPageProvider>
                <main className="bg-secondary-light w-full block h-full">
                  <WebVitals></WebVitals>
                  {children}
                  <div id="portal-root"></div>
                  <Analytics />
                </main>
              </LandingPageProvider>
            </StyledComponentsRegistry>
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
